### ISSUE TITLE
Suggestion: Option to Randomize Seed

### ISSUE THREAD

**Issue by altoiddealer** [thundaga/SD-webui-txt2img-script#8] opened 2023-06-15 00:39 UTC
Hello, I noticed when running the script that all of the images receive the same seed value.

Just suggesting that you include a checkbox to randomize seed for each image.

Reason being, I've ran a lot of batches over the course of time and so when I throw a directory of images at this script, I end up getting many duplicate outputs that go to the recycle bin.  Would be nice to potentially roll some more keepers.

**Comment by thundaga** [comment] 2023-06-15 00:46
By any chance did you check the box for "seed" value since its supposed to take the seed value of an already generated image from its metadata, if not it will take a default seed.

**Comment by altoiddealer** [comment] 2023-06-15 01:20
I was interested in having a different seed value than the initial image, but then the problem occurs that I mentioned.  Just a suggestion

**Comment by thundaga** [comment] 2023-06-15 02:15
Do you have the most recent update of the repository, check if the "Variation Seed" options work, if not I'll see what I can do

**Comment by altoiddealer** [comment] 2023-06-15 02:36
I’ll check that out.

I forgot to mention, this extension is amazing.  So glad you made this, and the whole thing is so well executed with the settings options, add/remove prompt functionality… simply amazing.  I was able to quickly and easily breathe nee life into my eatlier generations

**Comment by OPCOXE** [comment] 2023-06-16 16:06
I'm pretty sure adding a reset after the process while do you want.

I'll check that when I have time. But this would be a fix for you.

My idea if you want to test it (not final fix -> need a radio button but I'll check for that) :
```
177 proc = process_images(p)
178
179 p.seed = -1.0 # Adding this line 
180
191 # Reset Hires prompts (else the prompts of the first image will be used as Hires prompt for all the others)
192 p.hr_prompt = ""
```

**Comment by altoiddealer** [comment] 2023-06-16 16:33
Thanks, I’ll test that later today!

I may have another suggestion or two brewing :)

**Comment by OPCOXE** [comment] 2023-06-16 16:58
I'm not sure about your issue (or don't understand it) cause I just tested -1 in seed and didn't check the box to assign seed and it works.
Test the latest version but I'm pretty sure you had the seed defined to something else than -1.

For me there is nothing to change and it's working as intended.

**Comment by altoiddealer** [comment] 2023-06-16 21:20
> I'm not sure about your issue (or don't understand it) cause I just tested -1 in seed and didn't check the box to assign seed and it works (with latest version and no modification). Test the latest version but I'm pretty sure you had the seed defined to something else than -1.
> 
> For me there is nothing to change and it's working as intended.

I made sure I was on the latest version, and if I do not check "Seed" and I leave my seed value as -1 in A1111, all of the images that are processed in the Batch have the same seed value.

HOWEVER, I added that line of code to the script and tried again, and now all of the images have a random seed value.

That solved the problem :)

**Comment by thundaga** [comment] 2023-06-16 21:35
Awesome, glad to hear it worked out in the end 👍

**Comment by OPCOXE** [comment] 2023-06-17 07:16
The issue with that line it that if you define a seed in your prompt, it will be assign to the first image only.
I'm wondering where the issue come from, I'll re download the latest version and test it to see in case of but still it's strange cause I should have the same version.

**Comment by OPCOXE** [comment] 2023-06-17 08:21
Can you explain :

- How you do it ? (Use the script)
- How you check the seed is the same ?

I still have the same and can't figure out why you have a different behavior.

**Comment by altoiddealer** [comment] 2023-06-17 10:28
In A1111 / txt2img I click scripts, then choose your PNG Metadata script.  I click the tab for Batch from Folder.  I tick the option for Prompt, so it uses mainly the settings I’ve chosen in the webui.  Seed is -1 in the webui.  I set the input and output folders.

I then run the script.  All of the images are output with the same seed value.  I check them by dragging into PNGInfo tab

**Comment by OPCOXE** [comment] 2023-06-17 17:25
So you only use the option for prompt nothing else ?

**Comment by altoiddealer** [comment] 2023-06-17 18:07
Indeed, the output images all have identical seed values when I only use the option “prompt”.

**Comment by altoiddealer** [comment] 2023-06-17 19:12
PS - Have you considered making a similar script for img2img tab?

I now find myself wanting to do a batch img2img and the stock option in A1111 is apparently total shite.
From what I can tell, it leaves the prompt and negative prompt blank, does not add metadata... really just a non-functional mess.  A script like this would be a godsend for img2img

**Comment by thundaga** [comment] 2023-06-18 11:47
yeah that script is referenced in the readme, used it as useful base for making this one, pretty sure the metadata is part of the object that's being returned.
I'll close up this issue since it seems your problem was resolved, have a good day 👍

**Closed by thundaga** 2023-06-18 11:47 UTC

**Comment by altoiddealer** [comment] 2023-06-18 13:30
Thanks again!
